POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "duy",
    "password": "123456"
}

###

POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "tiennguyen",
    "password": "123456"
}

###

POST  http://localhost:5000/api/posts
Content-Type: application/json

{
    "title": "Learn React",
    "description": "abc",
    "url": "google.com",
    "status": "LEARNING"
}